mydata <- read.csv("exdata_data_household_power_consumption/household_power_consumption.txt",sep=";", dec=".",na.strings="?")
mydata$Date = as.Date(mydata$Date,format="%d/%m/%Y")
sub.mydata <- subset(mydata, mydata$Date >= "2007-02-01" & mydata$Date <= "2007-02-02")
datetime <- paste(as.Date(sub.mydata$Date),sub.mydata$Time)
sub.mydata$Datetime <- as.POSIXct(datetime)
plot(y=sub.mydata$Global_active_power, x=sub.mydata$Datetime,type="l",ylab="Global Active Power( kilowatts)", xlab="")
dev.copy(png,file="plot2.png", width=480, height=480)
dev.off()
cat("a plot has been created to the working directory")
